#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Install the ZoneX build and test dependencies on Ubuntu.
#
# The retry and timeout handling below is copied from threadx's
# scripts/install.sh rather than written fresh, and the reason is worth keeping
# with it.  Everything here reaches the network, and on the hosted runner pool
# that is not dependable: apt-get update stalled seven times in a single day
# there, once for more than two hours, each time with the mirror returning
# nothing and the fallback going silent.  Nothing bounded a fetch and nothing
# retried one, so a mirror being down cost a whole run rather than a few
# seconds.
#
# Each command is wrapped in timeout rather than left to bound itself.  apt's
# own Acquire timeouts were tried there first and did not help: a run still sat
# inside a single apt-get update for nine and a half minutes without producing
# a line.  Whatever apt waits on is not something Acquire::http::Timeout
# covers.  timeout does not care where the wait is.
#
# The Acquire options are kept anyway, since they make a slow mirror give up
# sooner.  set -e is on -- threadx's copy has no set -e, which let a failed
# update be carried forward into an install from a stale index, and the run
# then failed later somewhere less obvious.

set -euo pipefail

APT_OPTIONS=(-o Acquire::Retries=3
             -o Acquire::http::Timeout=20
             -o Acquire::https::Timeout=20)

# Two minutes per attempt, killed outright if it ignores the first signal.
# Three attempts plus backoff bounds a command at about six and a half minutes.
#
# timeout goes under sudo, not over it, so that it signals apt itself.
# Signalling sudo instead risks the kill landing on sudo while apt carries on
# holding the dpkg lock, which would leave every retry failing for a different
# reason than the one being retried.
TIMEOUT=(timeout --kill-after=10 120)

retry() {
    local attempt
    for attempt in 1 2 3; do
        if "$@"; then
            return 0
        fi
        echo "install.sh: '$*' failed or timed out on attempt ${attempt}"
        sleep $((attempt * 10))
    done
    echo "install.sh: '$*' failed after 3 attempts"
    return 1
}

# THE UPDATE IS NOT THE GATE, AND IT MUST NOT BE.  apt-get update fails if ANY
# configured repository serves a bad index, including ones this project does
# not use.  On a GitHub runner the image carries Google's and Microsoft's
# repositories, and a Hash Sum mismatch from Google's -- their CDN caught
# mid-publish, index and Release file eight hours apart -- failed this script
# three attempts running and turned a release build red over a browser nobody
# was installing.
#
# The alternative of disabling third-party sources before updating is wrong
# here: this script also runs on a contributor's own machine, where silently
# rewriting their apt configuration would be a far worse thing to do than
# tolerating a stale index.
#
# So a failed update WARNS and the install below is the gate.  Nothing is
# weakened by that: apt-get install still fails hard on a package it cannot
# find, so an archive that is genuinely unreachable still stops the script --
# one step later, and saying which package it could not get.
if ! retry sudo "${TIMEOUT[@]}" apt-get "${APT_OPTIONS[@]}" update; then
    echo ""
    echo "install.sh: apt-get update did not fully succeed."
    echo "install.sh: continuing, because a repository this project does not"
    echo "install.sh: use can fail an update.  The install below is the real"
    echo "install.sh: gate and fails if any package needed is unavailable."
    echo ""
fi
# gcc-14 and g++-14 EXPLICITLY, alongside build-essential.
#
# build-essential on ubuntu-24.04 is GCC 13, and GCC 14 is the compiler the
# project names as its Linux reference -- so installing only build-essential
# left CONTRIBUTING.md claiming a version CI did not have.  Both are
# installed: build-essential brings the rest of the toolchain furniture that
# gcc-14 alone does not.
#
# This does NOT rewire the default `gcc`, deliberately.  A dependency
# installer should not change which compiler every other build on the machine
# picks up.  The workflows name CC and CXX where the version has to be exact;
# a local build uses whatever `gcc` you have, which is what the "verified
# once it passes with the versions above" wording in CONTRIBUTING.md is for.
retry sudo "${TIMEOUT[@]}" apt-get "${APT_OPTIONS[@]}" install -y \
    --no-install-recommends \
    build-essential \
    cmake \
    g++-14 \
    gcc-14 \
    git \
    ninja-build \
    python3 \
    python3-pip

# gcovr is pinned exactly rather than floated.  The coverage percentage has to
# stay comparable between runs, and the denominator is a property of the tool
# as much as of the tree, so a tool that moves on its own makes every reported
# movement ambiguous.  It is moved by hand: this is a shell script, and no
# Dependabot ecosystem parses one.
#
# 8.6 is the version ThreadX pins, deliberately -- the two repositories report
# coverage against the same tool so the numbers can be compared.
retry "${TIMEOUT[@]}" python3 -m pip install --break-system-packages \
    --retries 3 --timeout 30 gcovr==8.6

# The Arm GNU Toolchain is NOT installed here.  It is fetched, checksum-checked
# and cached by the workflow that needs it, because a 500MB download does not
# belong in the step that installs six apt packages, and because CI and a
# developer machine want it in different places.  CONTRIBUTING.md names the
# pinned version; cmake/cortex_r52.cmake expects it under
# $HOME/toolchains/arm-gnu-toolchain-<version>-x86_64-arm-none-eabi.
